#!/usr/bin/env python3

import argparse
import csv
import math
import xml.etree.ElementTree as ET


def parse_float_rows(text, components):
    values = [float(value) for value in text.split()]
    if len(values) % components != 0:
        raise ValueError(f"Array length {len(values)} is not divisible by {components}.")
    return [tuple(values[i:i + components]) for i in range(0, len(values), components)]


def find_data_array(parent, name=None, components=None):
    for array in parent.findall("DataArray"):
        if name is not None and array.get("Name") != name:
            continue
        if components is not None and int(array.get("NumberOfComponents", "1")) != components:
            continue
        return array
    return None


def read_vtu_displacements(path):
    tree = ET.parse(path)
    piece = tree.getroot().find(".//Piece")
    if piece is None:
        raise ValueError("No VTK Piece found.")

    points = piece.find("Points")
    point_data = piece.find("PointData")
    if points is None or point_data is None:
        raise ValueError("VTU file must contain Points and PointData.")

    point_array = find_data_array(points, components=3)
    disp_array = find_data_array(point_data, name="Displacement", components=3)
    if point_array is None:
        raise ValueError("No 3-component Points array found.")
    if disp_array is None:
        raise ValueError("No 3-component PointData array named Displacement found.")

    coords = parse_float_rows(point_array.text or "", 3)
    displacements = parse_float_rows(disp_array.text or "", 3)
    if len(coords) != len(displacements):
        raise ValueError(f"Point count {len(coords)} != displacement count {len(displacements)}.")
    return coords, displacements


def write_csv(path, coords, displacements):
    with open(path, "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["node", "x", "y", "z", "ux", "uy", "uz", "u_mag"])
        for index, (coord, disp) in enumerate(zip(coords, displacements), start=1):
            magnitude = math.sqrt(disp[0] * disp[0] + disp[1] * disp[1] + disp[2] * disp[2])
            writer.writerow([index, coord[0], coord[1], coord[2], disp[0], disp[1], disp[2], magnitude])


def write_stappp_displacement_table(path, displacements):
    with open(path, "w") as f:
        f.write(" D I S P L A C E M E N T S\n\n")
        f.write("  NODE           X-DISPLACEMENT    Y-DISPLACEMENT    Z-DISPLACEMENT")
        f.write("    X-ROTATION        Y-ROTATION        Z-ROTATION\n")
        for index, disp in enumerate(displacements, start=1):
            f.write(f"{index:5d}        ")
            f.write(f"{disp[0]:18.10e}{disp[1]:18.10e}{disp[2]:18.10e}")
            f.write(f"{0.0:18.10e}{0.0:18.10e}{0.0:18.10e}\n")


def default_output(path, suffix, extension):
    if path.lower().endswith(".vtu"):
        return path[:-4] + suffix + extension
    return path + suffix + extension


def main():
    parser = argparse.ArgumentParser(description="Export nodal displacements from an ASCII VTU file.")
    parser.add_argument("vtu", help="Input .vtu file generated by STAP++")
    parser.add_argument("--csv", help="Write CSV file with node,x,y,z,ux,uy,uz,u_mag")
    parser.add_argument("--stappp-out", help="Write a STAP++-style displacement table")
    args = parser.parse_args()

    csv_output = args.csv
    stappp_output = args.stappp_out
    if not csv_output and not stappp_output:
        csv_output = default_output(args.vtu, "_node_displacements", ".csv")

    coords, displacements = read_vtu_displacements(args.vtu)
    if csv_output:
        write_csv(csv_output, coords, displacements)
        print(f"CSV written: {csv_output}")
    if stappp_output:
        write_stappp_displacement_table(stappp_output, displacements)
        print(f"STAP++ displacement table written: {stappp_output}")

    print(f"Nodes exported: {len(coords)}")


if __name__ == "__main__":
    main()
